language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.3'

before_script:
  - flags="-o"
  - composer install $flags

script:
  - php vendor/bin/psalm
  - php vendor/bin/php-cs-fixer fix --diff --dry-run --using-cache=no --config=.php_cs
  - php vendor/bin/phpunit -c phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
